export const categories = [
  {
    id: 1,
    name: "Biryani",
    image: "/placeholder.svg?height=80&width=80",
    count: 120,
  },
  {
    id: 2,
    name: "Pizza",
    image: "/placeholder.svg?height=80&width=80",
    count: 85,
  },
  {
    id: 3,
    name: "Burger",
    image: "/placeholder.svg?height=80&width=80",
    count: 95,
  },
  {
    id: 4,
    name: "Chinese",
    image: "/placeholder.svg?height=80&width=80",
    count: 110,
  },
  {
    id: 5,
    name: "South Indian",
    image: "/placeholder.svg?height=80&width=80",
    count: 75,
  },
  {
    id: 6,
    name: "Desserts",
    image: "/placeholder.svg?height=80&width=80",
    count: 60,
  },
  {
    id: 7,
    name: "North Indian",
    image: "/placeholder.svg?height=80&width=80",
    count: 130,
  },
  {
    id: 8,
    name: "Fast Food",
    image: "/placeholder.svg?height=80&width=80",
    count: 90,
  },
]

export const topRestaurants = [
  {
    id: 1,
    name: "Spicy Biryani House",
    image: "/placeholder.svg?height=200&width=300",
    rating: 4.5,
    deliveryTime: 30,
    category: "Biryani, Mughlai",
    deliveryFee: "Free",
    promoted: true,
    discount: "50% OFF",
  },
  {
    id: 2,
    name: "South Delight",
    image: "/placeholder.svg?height=200&width=300",
    rating: 4.2,
    deliveryTime: 25,
    category: "South Indian",
    deliveryFee: "₹20",
    promoted: true,
    discount: "40% OFF",
  },
  {
    id: 3,
    name: "Punjabi Zaika",
    image: "/placeholder.svg?height=200&width=300",
    rating: 4.6,
    deliveryTime: 35,
    category: "North Indian",
    deliveryFee: "Free",
    promoted: true,
    discount: "30% OFF",
  },
  {
    id: 4,
    name: "Pizza Corner",
    image: "/placeholder.svg?height=200&width=300",
    rating: 4.3,
    deliveryTime: 28,
    category: "Italian, Pizza",
    deliveryFee: "₹15",
    promoted: true,
    discount: "Buy 1 Get 1",
  },
  {
    id: 5,
    name: "Burger Junction",
    image: "/placeholder.svg?height=200&width=300",
    rating: 4.1,
    deliveryTime: 22,
    category: "Fast Food, Burgers",
    deliveryFee: "Free",
    promoted: true,
    discount: "25% OFF",
  },
]

export const allRestaurants = [
  {
    id: 1,
    name: "Spicy Biryani House",
    image: "/placeholder.svg?height=200&width=300",
    rating: 4.5,
    deliveryTime: 30,
    category: "Biryani, Mughlai",
    deliveryFee: "Free",
    discount: "50% OFF",
  },
  {
    id: 2,
    name: "South Delight",
    image: "/placeholder.svg?height=200&width=300",
    rating: 4.2,
    deliveryTime: 25,
    category: "South Indian",
    deliveryFee: "₹20",
    discount: "40% OFF",
  },
  {
    id: 3,
    name: "Punjabi Zaika",
    image: "/placeholder.svg?height=200&width=300",
    rating: 4.6,
    deliveryTime: 35,
    category: "North Indian",
    deliveryFee: "Free",
  },
  {
    id: 4,
    name: "Pizza Corner",
    image: "/placeholder.svg?height=200&width=300",
    rating: 4.3,
    deliveryTime: 28,
    category: "Italian, Pizza",
    deliveryFee: "₹15",
    discount: "Buy 1 Get 1",
  },
  {
    id: 5,
    name: "Burger Junction",
    image: "/placeholder.svg?height=200&width=300",
    rating: 4.1,
    deliveryTime: 22,
    category: "Fast Food, Burgers",
    deliveryFee: "Free",
    discount: "25% OFF",
  },
  {
    id: 6,
    name: "Tandoori Flames",
    image: "/placeholder.svg?height=200&width=300",
    rating: 4.4,
    deliveryTime: 32,
    category: "Grill, Tandoori",
    deliveryFee: "₹25",
  },
  {
    id: 7,
    name: "The Veggie Hub",
    image: "/placeholder.svg?height=200&width=300",
    rating: 4.0,
    deliveryTime: 28,
    category: "Vegetarian, Healthy",
    deliveryFee: "Free",
    discount: "20% OFF",
  },
  {
    id: 8,
    name: "Chinese Dragon",
    image: "/placeholder.svg?height=200&width=300",
    rating: 4.3,
    deliveryTime: 30,
    category: "Chinese, Asian",
    deliveryFee: "₹20",
  },
  {
    id: 9,
    name: "Dessert Paradise",
    image: "/placeholder.svg?height=200&width=300",
    rating: 4.7,
    deliveryTime: 20,
    category: "Desserts, Ice Cream",
    deliveryFee: "Free",
    discount: "30% OFF",
  },
  {
    id: 10,
    name: "Street Food Corner",
    image: "/placeholder.svg?height=200&width=300",
    rating: 4.2,
    deliveryTime: 25,
    category: "Street Food, Snacks",
    deliveryFee: "₹15",
  },
  {
    id: 11,
    name: "Healthy Bites",
    image: "/placeholder.svg?height=200&width=300",
    rating: 4.1,
    deliveryTime: 35,
    category: "Healthy, Salads",
    deliveryFee: "Free",
  },
  {
    id: 12,
    name: "Midnight Cravings",
    image: "/placeholder.svg?height=200&width=300",
    rating: 3.9,
    deliveryTime: 40,
    category: "Late Night, Snacks",
    deliveryFee: "₹30",
  },
]
